import './globals.css';
import { i18n } from '@/i18n-config';
import { BackgroundImage } from './background';

export function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children, params }: { children: React.ReactNode; params: { lang: string } }) {
  return (
    <html lang={params.lang}>
      <head />
      <body>
        <BackgroundImage />
        <div>{children}</div>
      </body>
    </html>
  );
}

export const revalidate = 3600;
